def reset_f():
    d = open('Decisions.txt', 'r+')
    d.truncate(0)
    d.close()
    e = open('Endings.txt', 'r+')
    e.truncate(0)
    e.close()
    r = open('Right.txt', 'r+')
    r.truncate(0)
    r.close()
    w = open('Wrong.txt', 'r+')
    w.truncate(0)
    w.close()
    es = open('Ending_Selec.txt', 'r+')
    es.truncate(0)
    es.close()
